---
title: "p8105_hw5_cp3384"
author: "Chenshuo Pan"
date: "2023-11-02"
output: github_document
---

```{r}
library(tidyverse)
```


# Question1
```{r}
homicide_data <- read.csv("data/homicide-data.csv")
```

```{r}
city_state_summary<- homicide_data%>%
  mutate(status = case_when(
    str_detect(disposition,"No") ==TRUE ~"unsolved homicides ",
    str_detect(disposition,"without") ==TRUE~"unsolved homicides ",
    TRUE   ~ "homicides "
  ))%>%
  mutate(city_state  = paste(city,state))%>%
  group_by(city_state)%>%
  summarise(unhomicides = sum(status == "unsolved homicides "),n = n())
```

```{r}
md <- city_state_summary %>%
  filter(city_state == "Baltimore MD")
unhomicides <- pull(md,unhomicides)
n <- pull(md,n)
md_test <- prop.test(unhomicides,n)

prop_test<-broom::tidy(md_test)

data.frame(city = "Baltimore MD",
          proportion = pull(prop_test,estimate),
          confidence_interval = paste("[",pull(prop_test,conf.low),
                                      pull(prop_test,conf.high),"]"))


```

```{r}


xx<-city_state_summary%>%
  mutate(test = map2(unhomicides,n,~prop.test(.x,.y)))%>%
  mutate(tidy = map(test,broom::tidy))%>%
  unnest(tidy)%>%
  mutate(confidence = paste("[",conf.low,conf.high,"]"))%>%
  select(city_state,estimate,conf.low,conf.high,confidence)


xx
```

```{r}
ggplot(xx,aes(y = reorder(city_state, estimate) ,x = estimate))+
  geom_point() +
  geom_errorbar(aes(xmin = conf.low,xmax = conf.high))+
  labs(x = "Proportion of Unsolved Homicides", y = "city and state", title = "Proportion of Unsolved Homicides by City") +
  theme_minimal()
```

# Question2


```{r,warning=FALSE}
longitudinal <- data.frame(file_name = paste("./data/",list.files(path = "./data",pattern = "[0-9].csv",),sep = ""))%>%
  mutate(x = map(file_name,read_csv))%>%
  unnest(x)%>%
  mutate(ID = str_sub(file_name,12,13),
         arm = str_sub(file_name,8,10))%>%
  select(-file_name)%>%
  relocate(arm,ID)

longitudinal
```

```{r}

longitudinal%>%
  pivot_longer(week_1:week_8,values_to = "value",names_to = "week")%>%
  mutate(week = str_sub(week,-1,-1),
         week = as.numeric(week))%>%
  ggplot(aes(x = week, y = value,color = ID))+
  geom_line()+
  facet_grid(~arm)+
  labs(x = "Week", y = "Value", title = "observations on each subject over time") +
  theme_minimal()
  
```
Comment:

# Question 3

```{r}
n = 30
sigma = 5
set.seed(1234)
mu =0



sim_mean_sd = function(n = 30, mu = 0, sigma = 5) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  test_result <- t.test(pull(sim_data,x), mu = 0)
  tidy_test_result <- broom::tidy(test_result)
  
  results <- tibble(mu_hat = pull(tidy_test_result,estimate),p.value = pull(tidy_test_result,p.value))
  
  return(results)
}


simulation = function(mu){
  
  output = vector("list", 5000)

  for(i in 1:5000){
    output[[i]] = sim_mean_sd(30,mu = mu,5)
  }
  
  sim_out = bind_rows(output)
  
  proportion = sim_out%>%
    mutate(reject = ifelse(p.value < 0.025 | p.value > 0.975, 1, 0))%>%
    summarise(prop = sum(reject)/5000,
              muhat = mean(mu_hat),
              null_muhat = mean(mu_hat[reject==1]))
  
  

  return(proportion)
}



sim_output = data.frame(mu = numeric(6), proportion= numeric(6),mu_hat= numeric(6),null= numeric(6))

for (i in 1:6) {
  a = simulation(mu = i)
  sim_output[i,"mu"] = i
  sim_output[i,"proportion"] = a[1,"prop"]
  sim_output[i,"mu_hat"] = a[1,"muhat"]
  sim_output[i,"null"] = a[1,"null_muhat"]
}
```

```{r}

summary_df <- data.frame(mu = numeric(6), proportion= numeric(6))
for (i in 1:6) {
  summary_df[,"mu"][i] = i
  summary_df[,"proportion"][i] = sim_output[[i]]
}

ggplot(summary_df,aes(x = mu , y =proportion))+
  geom_line()
```
```{r}

```


